### ISSUE TITLE
Implement Hindley-Milner type inference in Lint.hs

### ISSUE THREAD

**Issue by jwiegley** [haskell-nix/hnix#105]
Consider the following case where we lint a function abstraction:

```
hnix --check -e "{ x, y }: let z = x + y; in [ z (y + 2) ]"
(fromList [("x","int, string, path"),("y","int")] -> [int])
```

We can infer the return type and the type of `y` correctly, but we fail to infer `x` because we never re-examine `x + y` after later inferring the type of `y`. Instead we proceed linearly:

  1. See `x + y`, infer that x and y must both be either paths, strings or numbers.
  2. Later see `y + 2`, infer that y must be an integer.

We'd like to back-propagate this knowledge to every previous context where we'd seen `y` used, so that it can refine our understanding of the type of `x`.

Presently there's no support for this. We just box symbolic values in `IORef` so we can change their types as we see them used. I'm not sure what the best data representation would be to capture this "past knowledge", which might require re-evaluating based on some sort of data dependency tree. Thoughts on algorithms related to this problem would be most welcome.

Pinging @ryantrinkle. This is needed to complete #103.

**Comment by jwiegley** [comment]
I think this may just need the Hindley-Milner inference algorithm.

**Comment by jwiegley** [comment]
This looks like a promising starting point: https://github.com/kseo/poly_constraints

**Comment by Profpatsch** [comment]
There has been some substantial work going into gradual types for nix: https://www.youtube.com/watch?v=79dL7HgmW_k

Nix is very dynamic, what do you do when it’s impossible for HM to typecheck/infer something?

**Comment by jwiegley** [comment]
@Profpatsch I imagine we'll just have to treat it as a type that unifies with anything, which will degrade the usefulness of any error that we might report.

For example:

```
pkgs: with pkgs; x + 1
```

Although I know what the type of `x` should be here, I have no way of knowing if it's ever going to be scope, so I have to punt and constraint `pkgs` to the type of a set that at least contains an `x` of type int.

**Comment by jwiegley** [comment]
I just watched that video, and it seems strange to me that he never mentions HM, since at several points he gets very close and uses ideas found in that algorithm. Take this for example:

    x: x + 1

There’s no reason this needs a typing annotation to determine that the type of x is Int. The plus operator produces a typing constraint on both its arguments which is already enough to type this function.

Maybe I’m missing some of the subtleties he ran into in his implementation, though, but I’ll know soon.

**Comment by jwiegley** [comment]
I've added code for doing Hindley-Milner type inference in the `src/Nix/Type` directory. This code was written by Stephen Diehl and Kwang Yul Seo, which they released under an MIT license as the project [poly_constraints](https://github.com/kseo/poly_constraints):

The code is being added to `hnix` right now as mainly a placeholder, as it will need to be modified before it can be used. It's already very close, however, just need to flesh out the definition of `infer`, and the set of possible types.

**Comment by jwiegley** [comment]
This works well enough now to close this issue in favor of other issues with the implementation.

**Comment by thufschmitt** [comment]
> it seems strange to me that he never mentions HM

Just stumbled on this issue, but since I'm the one who did the talk, I might be able to answer this:

I'm well aware of HM, but we can't really use it here for (mostly) two reasons:

- We have a runtime representation of your types, and unification-based algorithms can't really take that into account. For example, if I have `x: if isInt x then (x+1) else (x && 1)`, I would have to unify the type of `x` with `Int` and `Bool` at the same time − that's more or less the same problem we have with GADT unification in haskell which forces us to add type-annotations.
- Unification doesn't really make sense anymore once you have arbitrary intersections since you can always unify two types by taking their intersection − so the function `x: x + x && x` would be well-typed, of type `Empty -> Int`, which isn't really helpful

**Comment by jwiegley** [comment]
@regnat Hi, and thanks for joining the discussion, you give some valid points. I wonder, though, whether HM can still be useful as a linting tool by adding restrictions that don't exist in the Nix language itself, like the expectation that both branches of an if statement must be of the same type.

**Comment by Profpatsch** [comment]
> I wonder, though, whether HM can still be useful as a linting tool by adding restrictions that don't exist in the Nix language itself, like the expectation that both branches of an if statement must be of the same type.

Personally, I tend to write all my nix expressions so that they could in theory pass HM type checking. Aka I avoid most dynamic features, with the exception of maybe accessing fields of attributes by using a string (`myset.${somestringvariable}`).

There is discussion about adding a similar feature to `dhall`, maybe their way of type-checking such constructs can be used as well: https://github.com/dhall-lang/dhall-lang/issues/169#issuecomment-395893113

**Comment by jwiegley** [comment]
@Profpatsch Agreed, I tend to do the same. Most of the lists I work with in Nix are always homogeneous, so that's another typing restriction we can add for "sane Nix".

The one I've found to be the most tricky -- and unfortunately it's used everywhere -- is dealing with sets. Not only are sets heterogeneous, but the set of keys they contain is an aspect of the "type" in some contexts (such as argument passing to functions).

The way the HM code in `hnix` handles this is by starting out restrictive: remembering every key and using type inference to narrow down the type at each key. But as you use the set in contexts where typing is not required, it degrades down to just "some set".

**Comment by thufschmitt** [comment]
@jwiegley Indeed, a simple HM-style type-system can be enough for a linting tool since most of the time you don't need the weird-crazy dynamic features of Nix.

Regarding sets, you can use row polymorphism which allows you to encode (to some extent) extensible records in an HM type-system. You can find an introduction [here](https://www.cl.cam.ac.uk/teaching/1415/L28/rows.pdf) (or an old proposal to add them to haskell [here](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.27.426&rep=rep1&type=pdf). I don't know how hard it is to imlement though.

**Comment by Septias** [comment]
I just found this issue, how far has the effort come?

**Comment by jwiegley** [comment]
So, a full HM type inference engine exists in the code now under `src/Nix/Type/Infer.hs`, and it can be used to type-check Nix code. What hasn't been done yet is to use this for the linter. That would involve adapting the symbolic evaluator currently in `Lint.hs`, to use the inference logic from `Infer.hs`, although likely it will need to do more than just work with types to find interesting linting problems.
