### ISSUE TITLE
Trying to understand the `NExprF` typeclass deriving mechanics

### ISSUE THREAD

**Issue by CMCDragonkai** [haskell-nix/hnix#321]
It appears that `Data.Functor.Classes` from transformers and `derive*` functions from deriving-compat are used together in order to help derive Prelude typeclasses for the type-level fix data structures, specifically `NExprF` (I like to think that this the AST). My understanding of this pattern comes from `recursion-schemes` package (specifically this blog post: http://blog.sumtypeofway.com/an-introduction-to-recursion-schemes/), which appears to try to resolve this problem of deriving typeclasses for the type-level fix data structures differently. I've googled for resources on understanding this problem, but can't find much. I'm hoping to get some documentation or commentary on what the rationale for choosing this pattern and why this method, and transformers and deriving-compat are chosen to solve this problem.

**Comment by timsears** [comment]
did you read [this post](http://newartisans.com/2018/04/win-for-recursion-schemes/) by @jwiegley ?

**Comment by CMCDragonkai** [comment]
I just did. Thanks for pointing it out, fascinating. However it didn't talk about all the deriving typeclass boilerplate that is in the code.

**Comment by jwiegley** [comment]
@CMCDragonkai Hi, I'm not clear on the exact question being asked. Can you quote some of the code you'd like explained?

Btw, NExprF isn't the AST, it's more like the "kernel" of the AST.  When `Fix` is applied to this kernel, then you have the tree structure that defines the "T" in AST.

**Comment by CMCDragonkai** [comment]
Hi @jwiegley I meant things like these:

https://github.com/haskell-nix/hnix/blob/738ef09bf9add0f0f21d7a72dd5ce31dbd200f67/src/Nix/Expr/Types.hs#L440-L462

Specifically why is this functionality is in `deriving-compat`. Also for myself as someone who didn't know about these features, how would I have ever known to use `deriving-compat` to deal with this problem, since the `deriving-compat` package does not even talk about this usage of their library (dealing with type-level fix data structures and requiring special typeclass derivations for the Prelude typeclasses (or that using a type alias of `type NExpr = Fix NExprF` doesn't propagate the functionality of the type classes)).

**Comment by Anton-Latukha** [comment]
Lately I walked the deriving list in `Expr`, and yes, most of what is - indeed requires TH deriving.

---

It seems that for some type classes for recursion schemes data types the metaprogramming space is needed.

Even for such simple thing as Peano numbers (`(Succ (Succ Nil))`) HOF versions of basic type classes can not be `deriving` or standalone deriving, or strategized. (still currently) A lift of the deriving procedure into TH space is required to derive them, for Peano for example that would be `Show1`, `Eq1`. I can not point towards moment why it is the case, but it is a case. I guess it is because of recursive data type nature that into the TH space arrives solved.

Indeed that particularly backward compatibility package `deriving-compat` has them (forward thinking instances) is pretty surprising. This TH deriving functionality probably belongs to be a separate package. If not to be included into TH itself. As I found it to be extremely useful.

---

Regarding that `NExpr` is a type synonym - it is still.

(I search for it) so far (strangely enough) there was no strong reason to make such core type as `NExpr` the newtype :shrug:.

**Comment by Anton-Latukha** [comment]
...

I think the reason to newtype would be exactly what I described above.

To show/eq the PeanoF, the TH derived `Show1, Eq1` instance are needed.

`*F` has no option but do a type class jump to `r` (itself). It becomes understandable that those `Show, Eq` are costly. newtype of a fixed type can infer(/have) the proper instances that do not require self-type class jump, so they become internally recursive, to which even some transformations probably can be applied.

To say, mere putting `newtype` over `Fix ..` probably should lead to faster type class instances code.

**Comment by Anton-Latukha** [comment]
Note: reduced the number of TH derived instances mentioned in: https://github.com/haskell-nix/hnix/issues/321#issuecomment-392734182
So of those now GHC can infer regularly.

---

> Specifically why is this functionality is in deriving-compat.

The package name is an idempotent thing, docs are proper, except leaning to that it is only backporting. It is because human nature, knowledge & motivation is not, thank God, an idempotent. Docs of it should be tweaked at least.

**Comment by Anton-Latukha** [comment]
When https://github.com/haskell-compat/deriving-compat/pull/36 closes - this report is resolved.

**Comment by Anton-Latukha** [comment]
Well, actually that thread already explains & solves the case.
