### ISSUE TITLE
Update from Megaparsec 6.5

### ISSUE THREAD

**Issue by jpdoyle** [haskell-nix/hnix#368]
Currently `hnix` depends on `megaparsec >=6.5 && <7.0`, and when running `nix-shell` I encountered a quickcheck error indicating a bug fixed in megaparsec 7.0 (https://github.com/mrkkrp/megaparsec/issues/323)

I'm not sure which things depend directly on megaparsec (I was doing this installation to just get started contributing), but since this bug is supposedly fixed in 7.0 that should be our target.

**Comment by jwiegley** [comment]
I'd be quite happy to upgrade to Megaparsec 7.0.

**Comment by Gabriella439** [comment]
I took a stab at this and it's a bit tricky.  The main challenge is that `megaparsec-7.*` changed `ParseError` to store `Int` instead of `NonEmpty SourcePos` which in turn requires refactoring the annotations that are threaded around `hnix`

**Comment by jwiegley** [comment]
@Gabriel439 Thanks for the attempt, Gabriel! Is there any other way to recover that source position information when an error happens? I wonder if the author removed that information to avoid storing something that most people weren't using...

**Comment by Gabriella439** [comment]
@jwiegley: I believe it's mainly for performance reasons.  This post provides more context for the motivation for the change:

https://markkarpov.com/post/megaparsec-more-speed-more-power.html

The changelog is also pretty detailed, although I haven't read it thoroughly yet:

http://hackage.haskell.org/package/megaparsec-7.0.1/changelog

What I did notice, though, is that the utilities for pretty-printing `ParseError` actually ignore that `Int` field now:

http://hackage.haskell.org/package/megaparsec-7.0.1/docs/src/Text.Megaparsec.Error.html#parseErrorTextPretty

My guess is that either:

* The source position information can be recovered from the `Int` (perhaps using `attachSourcePos`)
* The source position information can be recovered from other fields within the same constructor

**Comment by mrkkrp** [comment]
Hi, I haven't looked at the code, but if you want to have `SourcePos` as before then get it using [`getSourcePos`](https://hackage.haskell.org/package/megaparsec-7.0.1/docs/Text-Megaparsec.html#v:getSourcePos) from a running parser. Alternatively you could use `Int` offsets and recover `SourcePos` using `attachSourcePos`.

The users are mostly expected to work with `ParseErrorBundle`s now, not with `ParseError`s directly.

> What I did notice, though, is that the utilities for pretty-printing ParseError actually ignore that Int field now

Not quite true, `parseErrorTextPretty` always ignored that. Look at `parseErrorPretty` and you'll see that it print the `Int` as "offset".

If you have any questions please ask, I'm interested to help with the transition. (Because if it doesn't work well for you, then version 7 sucks!)

**Comment by domenkozar** [comment]
Fixed by https://github.com/haskell-nix/hnix/pull/380

**Comment by domenkozar** [comment]
Fixed in master.
