### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by kaii-zen** [haskell-nix/hnix#491]
Hello,

I tried to build the docker image according to the README and:

```
$ docker build -t hnix .
Sending build context to Docker daemon  1.403MB
Step 1/7 : FROM lnl7/nix:2.0
 ---> 000789f8ced3
Step 2/7 : WORKDIR /tmp/build
 ---> Using cache
 ---> 40d501c881be
Step 3/7 : COPY default.nix /tmp/build
 ---> Using cache
 ---> 0e718d3b5992
Step 4/7 : COPY package.yaml /tmp/build
COPY failed: stat /var/lib/docker/tmp/docker-builder149832881/package.yaml: no such file or directory
```

**Comment by vaibhavsagar** [comment]
Wow, it looks like that `Dockerfile` is out of date. Could you try my PR at https://github.com/haskell-nix/hnix/pull/492 and see if it fixes this issue for you? I'm building it right now.

**Comment by vaibhavsagar** [comment]
I was mistaken, my PR doesn't yet fix the issue.

**Comment by Anton-Latukha** [comment]
We removed `Dockerfile` like a half or year ago.

The containerization can be rediscussed when HNix can be installed on its own or there would be a pipeline for static compilation, otherwise, we also can resurrect & keep Dockerfile, but it was decided to remove it in the first place, and we would have gargantuan images.

On the merit that there is no Docker support - the Report "Docker build fails" is closed.

**Comment by kaii-zen** [comment]
I honestly don't even remember what this was for so feel free to close.

**Comment by Anton-Latukha** [comment]
@kreisys 
:heart: Thank you for your contribution to the community.
