### ISSUE TITLE
Push to stackage

### ISSUE THREAD

**Issue by Profpatsch** [haskell-nix/hnix#494]
It would be great to have `hnix` in Stackage. `haskellPackages` is pinned to Stackage, so it only guarantees that packages are not broken for Stackage. Because `hnix` has quite some dependencies (e.g. `megaparsec`), it is constantly broken in practice.

This is an active blocker for pushing https://github.com/Profpatsch/yarn2nix to `nixpkgs`, because it depends on `hnix`.

**Comment by flokli** [comment]
Would also love to see this happening :+1:

**Comment by flokli** [comment]
Tried a `stack init` on current master, the following version incompatibilites are present on `nightly-2019-04-09`:

```
* Partially matches nightly-2019-04-09
    hashing not found
        - hnix requires >=0.1.0 && <0.2
    hnix-store-core not found
        - hnix requires >=0.1.0 && <0.2
    http-client version 0.6.3 found
        - hnix requires >=0.5.14 && <0.6
    monadlist not found
        - hnix requires >=0.0.2 && <0.1
    ref-tf not found
        - hnix requires >=0.4.0 && <0.5
    these version 0.8 found
        - hnix requires >=0.7.5 && <0.8
    Using package flags:
        - hnix: optimize = False, profiling = False

```

**Comment by domenkozar** [comment]
Depends on #480

**Comment by jwiegley** [comment]
Just released hnix 0.6.1, let me know if this improves matters.

**Comment by flokli** [comment]
```
* Partially matches lts-13.17ranch to retain commits you create, you may
    hashing not found
        - hnix requires >=0.1.0 && <0.2
    hnix-store-core not found
        - hnix requires >=0.1.0 && <0.2
    monadlist not found
        - hnix requires >=0.0.2 && <0.1
    ref-tf not found
        - hnix requires >=0.4.0 && <0.5
    tasty-hedgehog not found
        - hnix requires -any
    Using package flags:
        - hnix: optimize = False, profiling = False

* Partially matches nightly-2019-04-21
    hashing not found
        - hnix requires >=0.1.0 && <0.2
    hnix-store-core not found
        - hnix requires >=0.1.0 && <0.2
    http-client version 0.6.4 found
        - hnix requires >=0.5.14 && <0.6
    monadlist not found
        - hnix requires >=0.0.2 && <0.1
    ref-tf not found
        - hnix requires >=0.4.0 && <0.5
    these version 0.8 found
        - hnix requires >=0.7.5 && <0.8
    Using package flags:
        - hnix: optimize = False, profiling = False
```

From a quick glimpse:

`hashing` should probably be replaced by `cryptonite`.

**Comment by Anton-Latukha** [comment]
HNix is on Stackage Nightly, since we in experimental/development stage and need to prioritize Nixpkgs - we can/should not wish better currently.
On that merit alone that HNix on Stackage - the Report really can be resolved.

---

I think it would be counter-productive to spread to software stores the not ready product. Type system still is not strict enough to follow language specification. The project should not advertise itself to users, which spread to software platforms is, the project should attract the Nix&Haskell specialists which live in Nixpkgs ecosystem, move to Stackage is counterproductive.

HNix prioritizes Hackage compatibility (since project still in development, we have not reached MVP/1.0), then Nixpkgs - those two systems create already hand full of incompatibility, advance for Stackage is not strategically reasonable or sound currently.

@Profpatsch I/we can solve this in other ways. Please describe the case in detail, so it gets understood.

If you are satisfied with Stackage Nightly - please, close the Report.

**Comment by Anton-Latukha** [comment]
[Update report:](https://repology.org/project/haskell:hnix/history)

IDK why, but HNix was removed from Stackage Nightly.

> 2020-07-16 04:03 | Stackage Nightly has caught up with the newest version (0.9.1)
> 2020-08-10 02:27 | Project removed from Stackage Nightly
>

**Comment by sjakobi** [comment]
@Anton-Latukha See https://github.com/commercialhaskell/stackage/issues/5535#issuecomment-670960714.

**Comment by Anton-Latukha** [comment]
HNix most interest is Hackage & Nixpkgs. Stackage game is not an HNix game but a possible side-gig.

HNix is a big complex developing project - and exactly for that reason, it is hard to introduce the Stackage complications into it.

Stackage inclusion into the Hackage <-> Nixpkgs loop complicates the maintenance very much, because introduces an additional hardwired dependency between Stackage <-> Nixpkgs. That would create a hardwired triangle of cross-dependenct situations.
An example of Stackage complications in much smaller dependency footprint is Store-Core situation is the https://github.com/haskell-nix/hnix-store/issues/104, https://github.com/commercialhaskell/stackage/issues/5766, https://github.com/haskell-hvr/cryptohash-sha512/pull/5, https://github.com/Anton-Latukha/cryptohash-sha512/tree/ghc-8.10, https://github.com/haskell-nix/hnix-store/issues/90, https://github.com/haskell-nix/hnix-store/pull/94, https://github.com/haskell-nix/hnix/commit/06b0fca9fd607eb2e995f003424e797a41ffa5b7 ... *this is not nearly the end of a list of links of work done to solve the situations*. *idk* what would've happened if at that moment HNix was on Stackage, we would probably stayed frozen, our CI tests for it would've been broken, we'd would needed to switch them off, and after everything switch them back, during that explaining the complications to the developers that submit PRs, and we wouldn't be able to ship to Nixpkgs *at all*, simply because of `hnix` being published on Stackage Nightly.
 
Stackage is a platform for stable projects, HNix is not one of them. 

To show that the project is partially done - HNix does not even have the `builtins` completed. HNix is simply not in a stable formed state, there was no promise of stability. There was no even changelog (when this thread was poster). I created ChangeLog around 0.8, and started to really support downstream use and migration instructions.
I do not want to complicate the project development processes simply because of the presence on Stackage.

Please do not post HNix to Stackage - that would be a huge disservice for us. This year a lot of effort was put to make the project state stable for development, and refactoring & development are the most important things now.

Maybe it would be reasonable to post HNix to Stackage after:
* core functionality is done & stabilized somewhat
* module hierarchy refactor & API refactor
* project split into Expressions, Evaluation, Executable, Extra.

That is somewhere between 1-2 years in HNix terms.

When the project would be clean and splits into 4 somewhat stable projects, that is exactly when we would be able to provide Stackage stability - and would be happy to go Stackage right at that moment.

**Comment by Profpatsch** [comment]
hnix is mostly always broken on nixpkgs.

If it was in stackage, it would be guaranteed not to be broken all the time, because that’s the way @peti built the nixpkgs haskell package set.

**Comment by Profpatsch** [comment]
If you think that you can make hnix always work in nixpkgs, I will take you by your word @Anton-Latukha. But I have my doubts.

**Comment by Profpatsch** [comment]
I have decided to migrate yarn2nix to a dumb string interpolation generator, because hnix is unusable at its current stage because of the regular breakage.

**Comment by Anton-Latukha** [comment]
Well, was nice to talk to you.

**Comment by Profpatsch** [comment]
hnix is broken in nixpkgs again.

**Comment by Anton-Latukha** [comment]
From the date of opening this topic, there were numerous HNix releases. 12 to be exact. For those 2 years I look at HNix reverse-dependencies, and for 2 years I see how `yarn2nix` is hardcoded to HNix `0.6.x`. Maybe in there is the cause.

Please check `yarn2nix` infrastructure. Isn't some dependencies hardcoded there? Maybe in a way one freezes the dependencies or the way it gets published to Hackage.

[Central Hydra CI builds shows HNix works nice in Nixpkgs](https://hydra.nixos.org/job/nixpkgs/trunk/haskellPackages.hnix.x86_64-linux/all), there is also shortcut to it on the frontpage of the project. In fact those logs would show everything was nice the previous time, and before that.
