### ISSUE TITLE
Set values are all "<CYCLE>"

### ISSUE THREAD

**Issue by sjakobi** [haskell-nix/hnix#663]
For some reason set values are printed as `"<CYCLE>"` although selecting the attribute results in the correct output.

```
hnix> { x = true; }
{ x = "<CYCLE>"; }
hnix> { x = true; }.x
true
```

**Comment by sorki** [comment]
This works correctly if you run repl with `--strict` which enables strict evaluation and calls `normalForm` before `prettyNValue`.

Not sure if defaulting to strict is a good idea.

**Comment by sorki** [comment]
PoC of `:set` for REPL making this configurable:

```
hnix> input
{ a = "<CYCLE>"; b = "<CYCLE>"; }
hnix> :set strict
hnix> input
{ a = 2; b = "test"; }
hnix> :set lazy
hnix> { x = 3; }
{ x = "<CYCLE>"; }
```

**Comment by sjakobi** [comment]
Thanks, @sorki! I wasn't aware of `--strict`, and `:set strict` looks really cool too! :)

I still feel like the current default behaviour is somewhat surprising:

* Does `<CYCLE>` simply mean that the value is a thunk?  To me, `<CYCLE>` suggests that the value can't be evaluated at all.

* Why should REPL users see such internals anyway? Is the primary purpose of the REPL to aid `hnix` developers with debugging the implementation?

I currently feel that when we prettyprint an expression, every part that is displayed should be forced.

**Comment by Anton-Latukha** [comment]
Currently, `hnix` default mode is a pretty-print, and that is strict.
REPL by default is lazy, since Nix is lazy.

That even devs get puzzled shows that CLI needs work: #737.

If REPL would be a subcommand - we can provide better docs for it, and modify and discuss cases of use, and modify their behavior.

I agree that:
```
hnix> { x = 3; }

{ x = "<CYCLE>"; }
```

Is excessive. For usability it shoulbe at least 1 level deeper, so at the very least those bindings are seen. I think it is reasonable to go 2-4 levels deep.

Included *this topic in the README: #738.

You absolutely right `<CYCLE>` name is obscure, and yelling in caps is rude, lets say it what it is - `<expr>`.

**Comment by Anton-Latukha** [comment]
Maybe `normalizeValue` is a responce. `NValue` is WHNM, there was NValueNF (normal form), but it was removed by John, `NValueNF` "is" `normalForm NValue`.
But not all `NValue` converge to normal form, and Nix allows arbitrary cycles - so `normalizeValue NValue`.

**Comment by Anton-Latukha** [comment]
Reformed into #777
