### ISSUE TITLE
NRecordType naming

### ISSUE THREAD

**Issue by sjakobi** [haskell-nix/hnix#667]
The `NRecordType` type introduced in https://github.com/haskell-nix/hnix/pull/500 distinguishes recursive and non-recursive sets:

 https://github.com/haskell-nix/hnix/blob/704323ecd6f0cec5b7ddd9e155599cbea2ae3cdb/src/Nix/Expr/Types.hs#L386-L388

Why does it have `Record` in its name though? What is a "record"?

I wonder whether `Recursivity` might be a better name.

CC @Infinisil

**Comment by Anton-Latukha** [comment]
True.

Maybe it was named for the possibility to read/write the code that processes record recursivity or not, aka "maybe just" reify nonrecursive record as constant.

In Nix there is no such atom as a record, every record belonging to some attrset. So in evaluation if ever record is processed - it needs to account the Set type into account, and then maybe should determine itself as recursive OR non-recursive, and their memory representations and mechs are obviously very different. It can be beneficial to represent non-recursive records as such in the long run, but currently I do not have an idea about the cost savings of it. But probably the savings in memory and processing can be quite tremendous.

As you noted:

```haskell
-- | 'NRecordType' distinguishes between recursive and non-recursive attribute
-- sets.
data NRecordType
  = NNonRecursive  -- ^ >     { ... }
  | NRecursive     -- ^ > rec { ... }
  deriving (Eq, Ord, Enum, Bounded, Generic, Typeable, Data, Show, Read,
            NFData, Hashable)
```

It is probably due to `rec` use, aka `rec` allows `set` records to be recursive.

I'd named it `NSetRecursivity`, `NIsSetRec` or `NSetType` - all of them are better then `NRecordType` as it used in `| NSet !NRecordType ![Binding r]`.

But, since as noted above record logic has the possibility to be handled internally at some point - it seems Ok to leave it as such currently. For example - the RecSet can be represented internally by two-component (Set && RecSet), where all `NNonRecursive` go into the first Set. The use of the `NRecordType` is currently exclusively limited to the module.

So `NSetRecursivity`, `NIsSetRec` or `NSetType` *idk*, `Recursivity` seems Ok, `RecRecursivity` seems...

I'd had both `NSetRecursivity` and `NRecRecursivity`, because both sets establish their type from up down, and the records reify their own type from down up, so that the records can be sorted by recursivity and recursive set type can be represented as `{{Constants} && {RecursiveFunctions}}`.

**Comment by Anton-Latukha** [comment]
And with languages we always need to think about:

`NSetRecursicity` is Expr,
`NRecordRecursivity` is not Expr, is not Parser, it can be reified only during Eval, so it belongs to the completely other part of the code.

**Comment by Anton-Latukha** [comment]
Found, it is `Recursivity = Recursive | NonRecursive` - it is all it is, it is a general flag/boolean type.

*(facepalm: it is what you suggested, was right all way along)*

That is also why I generally a fan of people contributing such simple things as PRs right ahead.
