### ISSUE TITLE
Version bounds on ref-tf too strict

### ISSUE THREAD

**Issue by sternenseemann** [haskell-nix/hnix#921]
~~`hnix` compiles with `ref-tf` 0.5, but the bounds on hackage forbid it at the moment.~~

**Comment by Anton-Latukha** [comment]
Yes: #918

It was done deliberately, because some instances were upstreamed to `ref-tf`, so to not have clashing instances and to get notification when `ref-tf` would do the relese - the bounds were put such.

The bounds would be `>=0.5`, since `ref-tf` releases have no bounds change in themself. If with `ref-tf` `0.5` having the same requirements, the `0.4` branch support nevertheless is seen as needed - please tell so. As currently hnix had not reached mpv, personnaly tend to save complexity of backward compatibility up to the point the backward compatibility would become important to hold.

**Comment by sternenseemann** [comment]
Alright, seems like I was mistaken. ~~Maybe that causes the mystery GHC failure without a logged error. Will try to pin `ref-tf` to < 0.5 for now, I don't think anything needs the newer version yet.~~

**Comment by Anton-Latukha** [comment]
The name of the report is proper. Project needs to be able to support new bounds.

During tinkering in such complex topics some of details are destined to slip-by, it is also ok to use `--keep-going` in Nix.
The best thing out of encounter is that we communicated & understood each other.

Soon would merge the `ref-tf` update into the main branch. But can not give estimate when would finish making the release, only process would show.

**Comment by sternenseemann** [comment]
There's no rush, backporting the patch was easy enough!

**Comment by Anton-Latukha** [comment]
Closed in the main branch by #918.
