### ISSUE TITLE
Cycle during CoercionToJson for attribute from recursive attrset

### ISSUE THREAD

**Issue by ony** [haskell-nix/hnix#941]
```nix
# sample.nix
rec {
  x = 42;
  y = x + 1;
}
```

```sh
hnix --eval sample.nix --strict -A y
# => 43
hnix --eval sample.nix --strict -A y --json
# => hnix: CoercionToJson "<CYCLE>"
hnix --eval sample.nix --strict -A x --json
# => hnix: CoercionToJson "<CYCLE>"
nix eval -f sample.nix y --json
# => 43
```

**Comment by Anton-Latukha** [comment]
Can you give `--long-version`?

From the output, I see it is an old release.

Seems like it got fixed in the main brunch.

**Comment by Anton-Latukha** [comment]
This is an old release, but in the new seems the same stuff.

Started investigating. Value `"cycle"` comes from `opaque`.

Even simpler, not recursive set also:
```
# sample.nix
{
  x = 42;
}
```
```sh
cabal v2-run hnix -- --eval sample.nix --strict -A x --json`
# indeed
hnix: CoercionToJson "<cycle>"
```

Meanwhile to remember also that currently:
```sh
cabal v2-run hnix -- --eval sample.nix -A x
Up to date
"<cycle>"
```

**Comment by layus** [comment]
i explored a bit further and the difference between nix and hnix is an optimisation performed by nix where it avoids thunking "immediate" values that require no computation. Constant numbers and strings mostly. See [`maybeThunk`](https://github.com/NixOS/nix/blob/293220bed5a75efc963e33c183787e87e55e28d9/src/libexpr/eval.cc#L829-L832).

HNix does not apply that optimisation because it's design does not allow to do that easily at the moment.
If you want to avoid thunks, you should consider using `--strict`.

Still, the confusion remains. A `"<cycle>"` without `--strict` is just a thunk (some unevaluated code). Nix makes a better job at highlighting that by calling them `<CODE>`.

```
# sample.nix
{
  x = 42;
  y = foo: "lol";
}
```
```sh
nix-instantiate --eval sample.nix          #=> { x = 42; y = <CODE>; }
./hnix sample.nix --eval                   #=> { x = "<cycle>"; y = "<cycle>"; }
nix-instantiate --eval sample.nix --strict #=> { x = 42; y = <LAMBDA>; }
./hnix sample.nix --eval --strict          #=> { x = 42; y = <closure>; }
```

**Comment by Anton-Latukha** [comment]
> Still, the confusion remains. A `"<cycle>"` without `--strict` is just a thunk (some unevaluated code). Nix makes a better job at highlighting that by calling them `<CODE>`.

Yes. https://github.com/haskell-nix/hnix/pull/824, so it was worse :laughing:, after that PR came another other one where I moved ^this particular `<expr>` stub beck to `<cycle>`, since it is what `opaque` is for, it is what `opaque` is semantically for us, `opaque & cycle` are equivalent to us due to halting problem of Nix language.

The first stage of the problem is semantic. `opaque` is used in `removeEffects`, it is where the reported output comes from, it is improper use of the `cycle`.

I remember reading the code or related code that causes this, indeed, when the expression is evaluated, if `--json` flag is present - the code strips evaluation from effects.
It is definitely tied to `removeEffects` use, `queryM` if thunk is not computed returns default value (the first arg). That is what happening.

**Comment by Anton-Latukha** [comment]
It is because printer has naive implementation:
https://github.com/haskell-nix/hnix/blob/99a38c40f29dd5b0d15e92311d418e7133a0f5d0/main/Main.hs#L157-L163

HNix by default is in lazy mode & that is not handled in the output, that is why:
```sh
cabal v2-run hnix -- --eval sample.nix -A x
"<thunk>" -- I already fixed (cycle -> thunk)
```
Strict version prints, but `--json` catches the control flow before `--strict` and they implemented as independent paths, so `--json` is lazy and because we not yet printing the lazy values out - this happens.

So #777 && make options to be combinators for printer.

**Comment by Anton-Latukha** [comment]
Naive fix is:
```haskell
      | json   opts = liftIO . Text.putStrLn . stringIgnoreContext         <=< nvalueToJSONNixString <=< normalForm
```

**Comment by Anton-Latukha** [comment]
Quickfix: https://github.com/haskell-nix/hnix/pull/942

**Comment by ony** [comment]
Wow. That's a quick reaction. :+1: 

It looks like I miscopied one example resulting in duplicate. The one that was missing in description:

```sh
hnix --eval sample.nix --strict --json  #=> {"x":42,"y":43}
```
*(not specifying attribute doesn't trigger issue)*  
*(seems like `--json` already imply `--strict`, so it is not required)* 

I also a bit concerned that most recent version of hnix gives `"<cycle>"` even without `--json` argument. And if I understand correctly, #942 affects only handling of `--json` argument in f2755083a5c6c274dd853bd6375e641de092bfcb . Rest commits seems like shouldn't affect functionality, except of maybe 4ddc0111f989321739792a7803c56689554f793e .

**Comment by Anton-Latukha** [comment]
*Hint: maybe revisit the above message someday.*

*(It can not pass the semantic checks in the interpreter, even if to turn the weak interpretability parameter to the maximal value.)*

**Comment by Anton-Latukha** [comment]
Ok. The topic is solved.
