### ISSUE TITLE
Maintainers for hnix in nixpkgs

### ISSUE THREAD

**Issue by expipiplus1** [haskell-nix/hnix#953]
Who is interested in becoming a maintainer for this package in nixpkgs?

It's a case of adding your handle and hnix to the list here: https://github.com/nixos/nixpkgs/blob/ff9db852f0761e05093abf090d4ecb399fea4324/pkgs/development/haskell-modules/configuration-hackage2nix/main.yaml#L131

Currently it's "transitively maintained" by me for update-nix-fetchgit and @Gabriel439 for dhall.

It's basically a case of fixing any errors which crop up from the haskell package set updates.

**Comment by Anton-Latukha** [comment]
Well, I largely *try* to go & submit changes into Nixpkgs, and say that I keep a promise. But frequently someone introduces a patch even before me & as on this Friday - I am guilty of releasing `hnix-store-{core,remote}` on Thursday & not getting a thought or remorse "would they automatically import into Nixpkgs & align to everything up", & my Friday was busy. Also after `peti` went away - I & probably many feel lost, I love `cdepillabout` & `maralorn` - they are doing rock star work up there, I am happy to meet changes but also it is normal that we feel lost. Please, write to `peti` farewell letters if someone missed to say goodbye to him, as I did, he would be right to not respond, but in reality - he would be glad to keep them & maybe even print them, a fond memory & a stack of proofs his work was not in vain & meant something.

---

Also, note to self - for `{Core,Remote}` still need to evolve https://github.com/haskell-nix/hnix-store/pull/89 to simplify this.

---

Since Nixpkgs is handled currently - I would add myself everywhere appropriate & go over Nixpkgs, once we release HNix GHC 9.0 support.

I didn't know that `haskellPackages` have a maintainer field in them.

**Comment by sternenseemann** [comment]
> I didn't know that haskellPackages have a maintainer field in them.

Unfortunately, this has been undocumented for a long time which we are aiming to change soon, so not knowing about it is to be expected, no worries!

**Comment by Anton-Latukha** [comment]
I opened a Nixpkgs patch declaring me as a contact/maintainer for `{hnix, hnix-store-core, hnix-store-remote}`.

**Comment by expipiplus1** [comment]
Thanks!
